protected/controllers/CarrosController.php
<?php

class CarrosController extends Controller
{
	/**
	 * @var CActiveRecord a instância do model Veiculo atualmente carregado.
	 * @see loadVeiculo().
	 */
	private $_veiculo;
	
	/**
	 * @var CActiveRecord a instância do model Evento atualmente carregado.
	 * @see loadEvento().
	 */
	private $_evento;
	
	/*
	 * Action default. Nesse caso, redireciona para a actionSemiNovos().
	 */
	public function actionIndex()
	{
		$this->redirect(array('semiNovos'));
	}
			
	/**
	 * Exibe a página de listagem de carros à pronta-entrega ou a página
	 * específica do carro solicitado por meio do método GET, se for o caso.
	 */
	public function actionProntaEntrega()
	{
		$model = new Veiculo();
		$model->unsetAttributes();
		
		if (isset($_GET['id'])) {
			$model  = $this->loadVeiculo();
			
			$testDriveForm = new TestDriveForm;
						
			if (isset($_POST['TestDriveForm'])) {
				$testDriveForm->attributes = $_POST['TestDriveForm'];
				$testDriveForm->veiculo = $model;
				if ($testDriveForm->validate())
					$this->enviarTestDriveForm($testDriveForm);
			}
		} else {
			$criteria = new CDbCriteria;
			$criteria->addCondition('ativo = true');
			// $criteria->addCondition('filtro = false');
			$criteria->addCondition('novo = true');
			$criteria->addCondition('prontaEntrega = true');
			
			if (isset($_GET['marca']))
				$model->marca = $_GET['marca'];

			if (isset($_GET['modelo']))
				$model->nome = $_GET['modelo'];

			$criteria->compare('marca', $model->marca);			
			$criteria->compare('nome', $model->nome);
			
			$criteria->order = 'promocao desc, valor';
			
			$dataProvider = new CActiveDataProvider('Veiculo', array(
				'pagination' => array(
					'pageSize' => '10'
				),
				'criteria' => $criteria
			));
		}
		
		$this->render('prontaEntrega', array(
			'model' => $model,
			'dataProvider' => isset($dataProvider) ? $dataProvider : false,
			'testDriveForm' => isset($testDriveForm) ? $testDriveForm : false
		));
	}
	
	/**
	 * Exibe a página de listagem de carros semi-novos ou a página
	 * específica do carro solicitado por meio do método GET, se for o caso.
	 */
	public function actionSemiNovos()
	{	
		$model = new Veiculo();
		$model->unsetAttributes();
		
		if (isset($_GET['id'])) {
			$model  = $this->loadVeiculo();
			
			$testDriveForm = new TestDriveForm;
						
			if (isset($_POST['TestDriveForm'])) {
				$testDriveForm->attributes = $_POST['TestDriveForm'];
				$testDriveForm->veiculo = $model;
				if ($testDriveForm->validate())
					$this->enviarTestDriveForm($testDriveForm);
			}
		} else {
			$criteria = new CDbCriteria;
			$criteria->addCondition('ativo = true');
			// $criteria->addCondition('filtro = false');
			$criteria->addCondition('novo = false');
			
			if (isset($_GET['marca']))
				$model->marca = $_GET['marca'];

			if (isset($_GET['modelo']))
				$model->nome = $_GET['modelo'];

			$criteria->compare('marca', $model->marca);			
			$criteria->compare('nome', $model->nome);
			
			$criteria->order = 'promocao desc, valor';
			
			$dataProvider = new CActiveDataProvider('Veiculo', array(
				'pagination' => array(
					'pageSize' => '10'
				),
				'criteria' => $criteria
			));
		}
		
		$this->render('semiNovos', array(
			'model' => $model,
			'dataProvider' => isset($dataProvider) ? $dataProvider : false,
			'testDriveForm' => isset($testDriveForm) ? $testDriveForm : false
		));
	}
	
	/**
	 * Exibe a página de listagem de carros em promoção ou a página
	 * específica do carro solicitado por meio do método GET, se for o caso.
	 */
	public function actionPromocoes()
	{
		$model = new Veiculo();
		$model->unsetAttributes();
		
		if (isset($_GET['id'])) {
			$model  = $this->loadVeiculo();
			
			$testDriveForm = new TestDriveForm;
						
			if (isset($_POST['TestDriveForm'])) {
				$testDriveForm->attributes = $_POST['TestDriveForm'];
				$testDriveForm->veiculo = $model;
				if ($testDriveForm->validate())
					$this->enviarTestDriveForm($testDriveForm);
			}
		} else {
			$criteria = new CDbCriteria;
			$criteria->addCondition('ativo = true');
			// $criteria->addCondition('filtro = false');
			$criteria->addCondition('promocao = true');
			
			if (isset($_GET['marca']))
				$model->marca = $_GET['marca'];

			if (isset($_GET['modelo']))
				$model->nome = $_GET['modelo'];

			$criteria->compare('marca', $model->marca);			
			$criteria->compare('nome', $model->nome);
			
			$criteria->order = 'promocao desc, valor';
			
			$dataProvider = new CActiveDataProvider('Veiculo', array(
				'pagination' => array(
					'pageSize' => '10'
				),
				'criteria' => $criteria
			));
		}
		
		$this->render('promocoes', array(
			'model' => $model,
			'dataProvider' => isset($dataProvider) ? $dataProvider : false,
			'testDriveForm' => isset($testDriveForm) ? $testDriveForm : false
		));
	}

	/**
	 * Retorna o model Veiculo baseado na PK obtida através do GET.
	 * Caso o veículo não seja encontrado, um erro 404 é disparado.
	 */
	public function loadVeiculo()
	{
		if ($this->_veiculo === null) {
			if (isset($_GET['id'])) {
				// $condition      = 'ativo = true AND filtro = false';
				$condition      = 'ativo = true';
				$this->_veiculo = Veiculo::model()->findByPk($_GET['id'], $condition);
			}
			if ($this->_veiculo === null)
				throw new CHttpException(404, 'O veículo requisitado não foi encontrado.');
		}
		return $this->_veiculo;
	}
	
	/**
	 * Retorna o model Evento baseado na PK obtida através do GET.
	 * Caso o evento não seja encontrado, um erro 404 é disparado.
	 */
	public function loadEvento()
	{
		if ($this->_evento === null) {
			if (isset($_GET['id'])) {
				$condition     = 'ativo = true';
				$this->_evento = Evento::model()->findByPk($_GET['id'], $condition);
			}
			if ($this->_evento === null)
				throw new CHttpException(404, 'O evento requisitado não foi encontrado.');
		}
		return $this->_evento;
	}
	
	/**
	 * Envia o formulário de teste drive.
	 */
	public function enviarTestDriveForm($model)
	{
		$message          = new YiiMailMessage;
		$message->view    = 'testDrive';
		$message->subject = 'Website > Solicitação de Teste Drive';
		$message->from    = Yii::app()->params['emailContato'];
		$message->AddReplyTo($model->email, $model->nome);
		
		foreach (explode(',', Yii::app()->params['emailTestDrive']) as $email) {
			$message->addTo(trim($email));			
		}
	
		$message->setBody(array('model' => $model), 'text/html');
		Yii::app()->user->setFlash('sucesso', '<strong>Obrigado!</strong> Sua solicitação foi enviada com sucesso. Por favor, aguarde o nosso contato.');
		Yii::app()->mail->send($message);
		$this->refresh();
	}
	
	/**
	 * Entrega uma lista de nomes de veículos filtrados pela marca e
	 * encapsulados pela tag HTML 'option' para ser usado com um select.
	 */
	public function actionGetNomeAjax()
	{
		$model = Veiculo::model()->getNomeList($_POST['marca']);
		
		echo CHtml::tag('option', array('value' => ''), 'Modelo', true);
		
		foreach ($model as $value) {
        	echo CHtml::tag('option', array('value' => $value), CHtml::encode($value), true);			
		}
    }
	
}

protected/controllers/EmpresaController.php
<?php

class EmpresaController extends Controller
{
	/**
	 * @var CActiveRecord a instância do model Evento atualmente carregado.
	 * @see loadEvento().
	 */
	private $_evento;
	
	/**
	 * @var CActiveRecord a instância do model Funcionario atualmente carregado.
	 * @see loadFuncionario().
	 */
	private $_funcionario;
	
	/*
	 * Action default. Nesse caso, redireciona para a actionQuemSomos().
	 */
	public function actionIndex()
	{
		$this->redirect(array(
			'quem-somos'
		));
	}
	
	/**
	 * Exibe a página 'Quem Somos'.
	 */
	public function actionQuemSomos()
	{		
		$this->render('quemSomos');	
	}
	
	/**
	 * Exibe a página 'Equipe de Vendas'.
	 */
	public function actionEquipeVendas()
	{		
		$criteria = new CDbCriteria;
		$criteria->addCondition('ativo = 1');
		$criteria->addCondition('equipe = 2');
		$criteria->order = 'nome';
		
		$dataProvider = new CActiveDataProvider('Funcionario', array(
			'pagination' => array(
				'pageSize' => '999'
			),
			'criteria' => $criteria
		));
		
		$this->render('equipeVendas', array(
			'dataProvider' => $dataProvider
		));
	}
	
	/**
	 * Exibe a página 'Fale com ...'.
	 * @param string $vendedor nome do vendedor.
	 */
	public function actionFaleCom($vendedor)
	{		
		$criteria = new CDbCriteria;
			
		if (!empty($vendedor))
			$model = Funcionario::model()->findByAttributes(array('nome' => $vendedor), 'ativo = true');		
		
		if (empty($model))
			throw new CHttpException(404, 'Desculpe, não foi encontrado nenhum vendedor com o nome informado.');	
		
		$faleComForm = new FaleComForm;
		
		if (isset($_POST['FaleComForm'])) {
			$faleComForm->attributes = $_POST['FaleComForm'];
			if ($faleComForm->validate()) {
				$faleComForm->funcionario = $model;
				$this->_enviarFaleComForm($faleComForm);	
			}
		}

		$this->render('faleCom', array(
			'model' => $model,
			'faleComForm' => $faleComForm
		));
	}
	
	
	/**
	 * Exibe a página 'Galeria de fotos'.
	 */
	public function actionGaleria()
	{
		$criteria = new CDbCriteria;
		$criteria->addCondition('ativo = 1');
		$criteria->addCondition('tipo = 1');
		$criteria->order = 'data desc';
		
		$dataProvider = new CActiveDataProvider('Evento', array(
			'pagination' => array(
				'pageSize' => '10'
			),
			'criteria' => $criteria
		));
		
		$this->render('galeria', array(
			'dataProvider' => $dataProvider
		));
	}
	
	/**
	 * Exibe a página 'Meio Ambiente'.
	 */
	public function actionMeioAmbiente()
	{				
		$model = new Evento();
		$model->unsetAttributes();
		
		$criteria = new CDbCriteria;
		$criteria->addCondition('ativo = 1');
		$criteria->addCondition('tipo = 4');
		$criteria->order = 'data desc';
		
		if (isset($_GET['id'])) {
			$model = $this->loadEvento();
		} else {
			if (!$model = Evento::model()->find($criteria))
				throw new CHttpException(404, 'Desculpe, Não há nenhum notícia no momento.');
		}
		
		$dataProvider = new CActiveDataProvider('Evento', array(
			'pagination' => array(
				'pageSize' => '5'
			),
			'criteria' => $criteria
		));
		
		$this->render('meioAmbiente', array(
			'model' => $model,
			'dataProvider' => $dataProvider
		));
	}

	/**
	 * Exibe a página 'Lançamentos'.
	 */
	public function actionLancamentos()
	{				
		$model = new Evento();
		$model->unsetAttributes();
		
		$criteria = new CDbCriteria;
		$criteria->addCondition('ativo = 1');
		$criteria->addCondition('tipo = 2');
		$criteria->order = 'data desc';
		
		if (isset($_GET['id'])) {
			$model = $this->loadEvento();
		} else {
			if (!$model = Evento::model()->find($criteria))
				throw new CHttpException(404, 'Desculpe, Não há nenhum lançamento no momento.');
		}
		
		$dataProvider = new CActiveDataProvider('Evento', array(
			'pagination' => array(
				'pageSize' => '10'
			),
			'criteria' => $criteria
		));
		
		$this->render('lancamentos', array(
			'model' => $model,
			'dataProvider' => $dataProvider
		));
	}
	
	/**
	 * Exibe a página 'noticias'.
	 */
	public function actionNoticias()
	{				
		$model = new Evento();
		$model->unsetAttributes();
		
		$criteria = new CDbCriteria;
		$criteria->addCondition('ativo = 1');
		$criteria->addCondition('tipo = 3');
		$criteria->order = 'data desc';
		
		if (isset($_GET['id'])) {
			$model = $this->loadEvento();
		} else {
			if (!$model = Evento::model()->find($criteria))
				throw new CHttpException(404, 'Desculpe, Não há nenhum lançamento no momento.');
		}
		
		$dataProvider = new CActiveDataProvider('Evento', array(
			'pagination' => array(
				'pageSize' => '10'
			),
			'criteria' => $criteria
		));
		
		$this->render('noticias', array(
			'model' => $model,
			'dataProvider' => $dataProvider
		));
	}
	
	/**
	 * Exibe a página 'Contato'.
	 */
	public function actionContato()
	{		
		$this->render('contato');	
	}
	
	/**
	 * Exibe a página 'Junte-se a nós'.
	 */
	public function actionTrabalheConosco()
	{
		$trabalheConoscoForm = new TrabalheConoscoForm;
	
		if (isset($_POST['TrabalheConoscoForm'])) {
			$trabalheConoscoForm->attributes = $_POST['TrabalheConoscoForm'];
			if ($trabalheConoscoForm->validate())
				$this->enviarTrabalheConoscoForm($trabalheConoscoForm);
		}
		
		$this->render('trabalheConosco', array(
			'trabalheConoscoForm' => $trabalheConoscoForm		
		));	
	}
	
	/**
	 * Retorna o model Evento baseado na PK obtida através do GET.
	 * Caso o evento não seja encontrado, um erro 404 é disparado.
	 */
	public function loadEvento()
	{
		if ($this->_evento === null) {
			if (isset($_GET['id'])) {
				$condition     = 'ativo = true';
				$this->_evento = Evento::model()->findByPk($_GET['id'], $condition);
			}
			if ($this->_evento === null)
				throw new CHttpException(404, 'O evento requisitado não foi encontrado.');
		}
		return $this->_evento;
	}
	
	/**
	 * Envia o formulário TrabalheConoscoForm.
	 */
	public function enviarTrabalheConoscoForm($model)
	{
		$message          = new YiiMailMessage;
		$message->view    = 'trabalheConosco';
		$message->subject = 'Website > Trabalhe Conosco';
		$message->from    = Yii::app()->params['emailContato'];
		$message->AddReplyTo($model->email, $model->nome);
		
		foreach (explode(',', Yii::app()->params['emailTrabalheConosco']) as $email) {
			$message->addTo(trim($email));			
		}
		
		$message->setBody(array('model' => $model), 'text/html');
		Yii::app()->user->setFlash('sucesso', '<strong>Obrigado!</strong> Sua mensagem foi enviada com sucesso. Por favor, aguarde o nosso contato.');
		Yii::app()->mail->send($message);
		$this->refresh();
	}
	
	/**
	 * Envia o formulário FaleCom.
	 */
	private function _enviarFaleComForm($model)
	{
		$message          = new YiiMailMessage;
		$message->view    = 'faleCom';
		$message->subject = 'Website > Fale com ' . $model->nome;
		$message->from    =  $model->funcionario->email;
		$message->addTo($model->funcionario->email);		
		$message->AddReplyTo($model->email, $model->nome);
		$message->setBody(array('model' => $model), 'text/html');
		Yii::app()->user->setFlash('sucesso', '<strong>Obrigado!</strong> Sua mensagem foi enviada com sucesso. Por favor, aguarde o nosso contato.');
		Yii::app()->mail->send($message);
		$this->refresh();
	}

}

protected/controllers/HomeController.php
<?php

class HomeController extends Controller
{
	/**
	 * @var string the default layout for the controller view. Defaults to 'home'.
	 */
	public $layout = 'home';
	
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha' => array(
				'class' => 'CCaptchaAction',
				'backColor' => 0xFFFFFF
			)
		);
	}
	
	/*
	 * Action default caso não esteja explicita nenhuma outra na url.
	 */
	public function actionIndex()
	{
		Yii::app()->user->setReturnUrl(Yii::app()->baseUrl);
		
		$model = new Veiculo();
		$model->unsetAttributes();
		
		// carros em promoção
		$criteria = new CDbCriteria;
		$criteria->addCondition('ativo = true');
		$criteria->addCondition('filtro = false');
		$criteria->addCondition('promocao = true');
		$criteria->addCondition('imgDestaque <> \'\'');
		$criteria->order = 'rand()';
		
		$dataProvider = new CActiveDataProvider('Veiculo', array(
			'pagination' => array(
				'pageSize' => '3'
			),
			'criteria' => $criteria
		));
		
		// carros novos
		$criteria = new CDbCriteria;
		$criteria->addCondition('ativo = true');
		$criteria->addCondition('filtro = true');
		$criteria->addCondition('prontaEntrega = true');
		$criteria->order = 'rand()';
		
		$carrosNovosModel = Veiculo::model()->findAll($criteria);
				
		$this->render('index', array(
			'model' => $model,
			'dataProvider' => $dataProvider,
			'carrosNovosModel' => $carrosNovosModel
		));
	}

	/*
	 * Exibe a página 'Assine nossas newsletters'.
	 */
	public function actionAssineNossasNewsletters()
	{
		if (Yii::app()->request->urlReferrer !== Yii::app()->request->hostInfo . Yii::app()->request->requestUri)
			Yii::app()->user->setReturnUrl(Yii::app()->request->urlReferrer);
			
		if (isset($_POST['email'])) {
			$newsletterForm = new NewsletterForm;
			$newsletterForm->email = $_POST['email'];
			if ($newsletterForm->validate()) {
				$message          = new YiiMailMessage;
				$message->view    = 'newsletter';
				$message->subject = 'Website > Assinatura de Newsletter';
				$message->from    = Yii::app()->params['emailContato'];
				$message->AddReplyTo($_POST['email']);
				
				foreach (explode(',', Yii::app()->params['emailNewsletter']) as $email) {
					$message->addTo(trim($email));			
				}

				$message->setBody(array('email' => $_POST['email']), 'text/html');
				
				Yii::app()->mail->send($message);	
				Yii::app()->user->setFlash('sucesso', '<strong>Obrigado!</strong> Sua solicitação foi enviada com sucesso.');				
			} else {
				Yii::app()->user->setFlash('erro', '<strong>Ops...</strong> ' . $newsletterForm->getError('email'));	
			}
		} 
		//$this->redirect(Yii::app()->user->returnUrl);	
		$this->redirect(Yii::app()->user->returnUrl);
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if ($error = Yii::app()->errorHandler->error) {
			if (Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}
		
}

protected/controllers/SegurosController.php
<?php

class SegurosController extends Controller
{
	/*
	 * Action default caso não esteja explicita nenhuma outra na url.
	 * Nesse caso, redireciona para a actionAgoge().
	 */
	public function actionIndex()
	{
		$this->redirect(array(
			'agoge'
		));
	}
	
	/**
	 * Exibe a página 'Agoge'.
	 */
	public function actionAgoge()
	{		
		$this->render('agoge');	
	}
}

protected/views/layouts/_footer.php
<?php if ($this->footer) : ?>

<footer id="footer">
	<section class="newsletter">
		<div class="container">
			<div class="row">
				<div class="span5">
					<a href="<?php echo Yii::app()->createUrl('/empresa/equipe-vendas'); ?>">
						<?php echo CHtml::image(Yii::app()->baseUrl . '/images/icon-deficiente-56.png', '', array('class' => 'pull-left')); ?>
						<h5>Isenção de impostos</h5>	
						<p>Consulte as condições especiais<br />
						para portadores de deficiência.</p>
					</a>
				</div>
				<div class="span4">
					<?php echo CHtml::image(Yii::app()->baseUrl . '/images/icon-news-56.png', '', array('class' => 'pull-left')); ?>
					<h5>News Fiat Applàuso</h5>	
					<p>Cadastre seu e-mail para<br />
					receber nossa newsletter:</p>
				</div>
				<div class="span3">
					<?php echo CHtml::form($this->createUrl('home/assine-nossas-newsletters'), 'post'); ?>	
					<div class="input-append">
          				<?php echo CHtml::textField('email', '', array('placeholder' => 'digite o seu e-mail')); ?>
          				<?php echo CHtml::htmlButton('Enviar', array('type' => 'submit', 'class' => 'btn')); ?>
        			</div>
					<?php echo CHtml::endform() ?> 	
				</div>
			</div>
		</div>
	</section>	
	<section class="main">
		<div class="container">
			<div class="row">
				<div class="span2">
					<h5>Carros</h5>
					<?php $this->widget('Menu', array(
						'type' => 'pills',
						'stacked' => true,
						'items' => array(
							array('label' => 'Novos Pronta-entrega', 'url' => array('/carros/pronta-entrega')),
							array('label' => 'Semi-novos', 'url' => array('/carros/semi-novos')),
							array('label' => 'Promoções', 'url' => array('/carros/promocoes'))
						),
					)); ?>
				</div>
				<div class="span2">
					<h5>Serviços</h5>
					<?php $this->widget('Menu', array(
						'type' => 'pills',
						'stacked' => true,
						'items' => array(
							array('label' => 'Assistência Técnica', 'url' => array('/servicos/assistencia-tecnica')),
							array('label' => 'Agende sua revisão', 'url' => array('/servicos/agende-revisao')),
							array('label' => 'Peças Originais', 'url' => array('/servicos/pecas-originais')),
							array('label' => 'Frotista', 'url' => array('/servicos/frotista')),
							array('label' => 'Consórcio', 'url' => array('/servicos/consorcio')),
							array('label' => 'Fiat Fashion', 'url' => array('/servicos/fashion'))
						),
					)); ?>
				</div>
				<div class="span2">
					<h5>Empresa</h5>
					<?php $this->widget('Menu', array(
						'type' => 'pills',
						'stacked' => true,
						'items' => array(
							array('label' => 'Quem Somos', 'url' => array('/empresa/quem-somos')),
							array('label' => 'Equipe de Vendas', 'url' => array('/empresa/equipe-vendas')),
							array('label' => 'Meio Ambiente', 'url' => array('/empresa/meio-ambiente')),
							array('label' => 'Lançamentos', 'url' => array('/empresa/lancamentos')),
							array('label' => 'Noticias', 'url' => array('/empresa/noticias')),
							array('label' => 'Galeria de fotos', 'url' => array('/empresa/galeria')),
							array('label' => 'Contato', 'url' => array('/empresa/contato')),
							array('label' => 'Junte-se a nós', 'url' => array('/empresa/trabalhe-conosco'))
						),
					)); ?>
				</div>
				<div class="span2">
					<h5>Seguros</h5>
					<?php $this->widget('Menu', array(
						'type' => 'pills',
						'stacked' => true,
						'items' => array(
							array('label' => 'Agogê', 'url' => array('/seguros/agoge'))
						)
					)); ?>
				</div>
				<div class="span4">
					<div class="facebook pull-right">
					<div class="fb-like-box" data-href="<?php echo Yii::app()->params['linkFacebook']; ?>" data-width="260" data-height="218" data-show-faces="true" data-stream="false" data-header="true"></div>						
					</div>
				</div><!-- facebook -->
			</div>
			<div class=row>
				<div class="span3">
					<a class="logo" href="<?php echo Yii::app()->baseUrl; ?>" title="<?php echo CHtml::encode(Yii::app()->name); ?>">
						<?php echo CHtml::image(Yii::app()->baseUrl . '/images/logo.png', CHtml::encode(Yii::app()->name), array('height' => '50')); ?>
					</a>
				</div>
				<div class="span4">
					<div class="phone"><?php echo CHtml::encode(Yii::app()->params['foneContato']); ?></div>			
				</div>
				<div class="span4">
					<address>
						<strong>e-mail: <?php echo CHtml::link(Yii::app()->params['emailContato'], 'mailto:' . Yii::app()->params['emailContato']); ?></strong><br />
						<?php echo CHtml::encode(Yii::app()->params['endereco']); ?>
					<address>
				</div>	
				<div class="span1">
					<a href="<?php echo Yii::app()->baseUrl; ?>" title="Applàuso Concessionária Fiat Tatuí">
						<?php echo CHtml::image(Yii::app()->baseUrl . '/images/logo-fiat.png', 'Applàuso Concessionária Fiat Tatuí', array('height' => '50')); ?>
					</a>			
				</div>
			</div>
		</div>
	</section>
	<div id="copy">
		<div class="container">
			<p>Copyright &copy; <?php echo date('Y'); ?>. <?php echo CHtml::encode(Yii::app()->name); ?>. Todos os direitos reservados.</p>
		</div>
	</div>
</footer><!-- footer -->
<?php endif; ?>

<span class='st_email_hcount' displayText='Email'></span>
<span class='st_facebook_hcount' displayText='Facebook'></span>
<span class='st_twitter_hcount' displayText='Tweet'></span>
<span class='st_plusone_hcount' displayText='Google +1'></span>

<div id="ajax-loading"></div>
<?php
Yii::app()->clientScript->registerScript('ajax-loading', '
jQuery(\'#ajax-loading\').bind(\'ajaxSend\',function(){
	$(\'body\').addClass(\'loading\');
}).bind(\'ajaxComplete\',function(){
	$(\'body\').removeClass(\'loading\');
});
');
?>

<div id="fb-root"></div>
<?php 
Yii::app()->clientScript->registerScript('fb-like-box', '
(function(d, s, id) {
	var js, fjs = d.getElementsByTagName(s)[0];
	if (d.getElementById(id)) return;
	js = d.createElement(s); js.id = id;
	js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
	fjs.parentNode.insertBefore(js, fjs);
}(document, \'script\', \'facebook-jssdk\'));
');
?>

</body>
</html>

protected/views/layouts/main.php
<?php $this->renderPartial('/layouts/_header'); ?> 

<div id="page">
	<div id="main">
		<div class="container">
			<div id="content">							
				<?php $this->renderPartial('/layouts/_flash'); ?> 
				
				<?php if ($this->content) : ?>
					
				<?php echo $content; ?>
				
				<?php endif; ?>	
			</div><!-- content -->		
		</div>
	</div><!-- main -->
</div><!-- page -->

<section id="bottom">
	<div class="container">
		<div class="box banners">
			<div class="row">
				<div class="span">
					<a href="<?php echo Yii::app()->createUrl('/seguros/agoge'); ?>">
						<?php echo CHtml::image(Yii::app()->baseUrl . '/images/box-agoge.png'); ?>
					</a>
				</div>
				<div class="span">
					<a href="<?php echo Yii::app()->createUrl('/servicos/assistencia-tecnica'); ?>">
						<?php echo CHtml::image(Yii::app()->baseUrl . '/images/box-assistencia-tecnica.png'); ?>
					</a>
				</div>
				<div class="span">
					<a href="<?php echo Yii::app()->createUrl('/carros/pronta-entrega', array('marca' => 'fiat', 'modelo' => 'ducato')); ?>">
						<?php echo CHtml::image(Yii::app()->baseUrl . '/images/box-ducato.png'); ?>
					</a>
				</div>
			</div>
			<div class="row">
				<div class="span">
					<a href="<?php echo Yii::app()->createUrl('/servicos/fashion'); ?>">
						<?php echo CHtml::image(Yii::app()->baseUrl . '/images/box-fashion.png'); ?>
					</a>
				</div>
			</div>
		</div>	
	</div>
</section>

<?php $this->renderPartial('/layouts/_footer'); ?> 